
export const ListData = [
  {
    id: 1,
    title: "A great apartment next to the beach",
    img: "https://www.cntraveler.com/story/our-favorite-hotel-rooms-with-a-view",
    bedroom: 4,
    bathroom: 2,
    price: 3000,
    address: "33 Juson Street 24",
    latitude: 46.5987,
    longitude: -0.32165,
  },
  {
    id: 2,
    title: "Luxury condo with ocean view",
    img: "./photos/th (2).jpeg",
    bedroom: 3,
    bathroom: 2,
    price: 4500,
    address: "45 Ocean Avenue",
    latitude: 47.6021,
    longitude: -0.12345,
  },
  {
    id: 3,
    title: "Cozy bungalow near the shore",
    img: "http://example.com/image3.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 2500,
    address: "12 Shoreline Drive",
    latitude: 48.0034,
    longitude: -0.54321,
  },
  {
    id: 4,
    title: "Spacious villa with beach access",
    img: "http://example.com/image4.jpg",
    bedroom: 5,
    bathroom: 3,
    price: 5500,
    address: "89 Beachside Lane",
    latitude: 46.8976,
    longitude: -0.6789,
  },
  {
    id: 5,
    title: "Modern apartment close to the sea",
    img: "http://example.com/image5.jpg",
    bedroom: 3,
    bathroom: 2,
    price: 3200,
    address: "23 Coastal Road",
    latitude: 47.2068,
    longitude: -0.45678,
  },
  {
    id: 6,
    title: "Charming house with sea view",
    img: "http://example.com/image6.jpg",
    bedroom: 4,
    bathroom: 2,
    price: 4100,
    address: "56 Seaview Street",
    latitude: 48.4567,
    longitude: -0.98765,
  },
  {
    id: 7,
    title: "Beachfront penthouse suite",
    img: "http://example.com/image7.jpg",
    bedroom: 3,
    bathroom: 3,
    price: 6000,
    address: "101 Oceanfront Blvd",
    latitude: 46.789,
    longitude: -0.65432,
  },
  {
    id: 8,
    title: "Quaint cottage by the beach",
    img: "http://example.com/image8.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 2800,
    address: "75 Sandy Shores",
    latitude: 47.1234,
    longitude: -0.76543,
  },
  {
    id: 9,
    title: "Elegant townhouse near the coast",
    img: "http://example.com/image9.jpg",
    bedroom: 4,
    bathroom: 2,
    price: 3900,
    address: "14 Harbor Lane",
    latitude: 46.3456,
    longitude: -0.87654,
  },
  {
    id: 10,
    title: "Stylish loft with sea view",
    img: "http://example.com/image10.jpg",
    bedroom: 3,
    bathroom: 2,
    price: 3100,
    address: "67 Maritime Street",
    latitude: 47.5678,
    longitude: -0.54321,
  },
  {
    id: 11,
    title: "Seaside cabin with private beach",
    img: "http://example.com/image11.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 3400,
    address: "88 Coastal Cabin Road",
    latitude: 46.8901,
    longitude: -0.23456,
  },
  {
    id: 12,
    title: "Luxurious beach house",
    img: "http://example.com/image12.jpg",
    bedroom: 5,
    bathroom: 4,
    price: 7000,
    address: "90 Paradise Cove",
    latitude: 47.6543,
    longitude: -0.6789,
  },
  {
    id: 13,
    title: "Modern condo with sea view",
    img: "http://example.com/image13.jpg",
    bedroom: 3,
    bathroom: 2,
    price: 3600,
    address: "11 Seascape Drive",
    latitude: 48.321,
    longitude: -0.78901,
  },
  {
    id: 14,
    title: "Chic apartment near the ocean",
    img: "http://example.com/image14.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 2900,
    address: "29 Atlantic Avenue",
    latitude: 46.6543,
    longitude: -0.12345,
  },
  {
    id: 15,
    title: "Beach house with stunning views",
    img: "http://example.com/image15.jpg",
    bedroom: 4,
    bathroom: 3,
    price: 5300,
    address: "54 Ocean View Road",
    latitude: 47.789,
    longitude: -0.23456,
  },
  {
    id: 16,
    title: "Cozy beachfront cottage",
    img: "http://example.com/image16.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 2700,
    address: "43 Sandy Lane",
    latitude: 48.5678,
    longitude: -0.34567,
  },
  {
    id: 17,
    title: "Spacious duplex by the sea",
    img: "http://example.com/image17.jpg",
    bedroom: 3,
    bathroom: 2,
    price: 3800,
    address: "17 Shoreline Boulevard",
    latitude: 46.8901,
    longitude: -0.45678,
  },
  {
    id: 18,
    title: "Elegant villa with sea access",
    img: "http://example.com/image18.jpg",
    bedroom: 5,
    bathroom: 4,
    price: 6200,
    address: "71 Ocean Drive",
    latitude: 47.4321,
    longitude: -0.56789,
  },
  {
    id: 19,
    title: "Modern townhouse with sea view",
    img: "http://example.com/image19.jpg",
    bedroom: 3,
    bathroom: 2,
    price: 3400,
    address: "6 Bay Avenue",
    latitude: 48.2109,
    longitude: -0.6789,
  },
  {
    id: 20,
    title: "Beachfront apartment with balcony",
    img: "http://example.com/image20.jpg",
    bedroom: 2,
    bathroom: 1,
    price: 3100,
    address: "15 Beachside Boulevard",
    latitude: 46.789,
    longitude: -0.78901,
  },
];
